-- ============================================================
-- 20260430000000_fix_visibility_enum.sql — DEPRECATED / INACTIVE
-- ============================================================
-- This migration has been deprecated and neutralized to resolve the 
-- Visibility Enum Inconsistency (Bug 8). 
-- 
-- RATIONALE:
-- The application codebase and newer migrations (e.g., May 2026 features) 
-- rely extensively on the original rich visibility enum values:
-- ('org_wide', 'department', 'bi_accessible', 'confidential', 'restricted').
-- Running this legacy migration would destroy the RLS policies and corrupt 
-- the visibility data, leading to systematic access control failures.
-- ============================================================

